# Generated by Django 3.1.7 on 2021-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoNepaliApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='thumbnail',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
